--Based on Emp table Columns are EmpNo, Ename, Job, Salary, Commission, DeptNO 
--Insert 5 records by stroring Null value in some records for commission column. 
CREATE TABLE EMP(
    EMPNO INT,
    ENAME VARCHAR(30),
    JOB_NAME VARCHAR(20),
    SALARY INT,
    COMMISSION FLOAT,
    DEPTNO INT
);
INSERT INTO EMP VALUES (101, 'Matt Murdock', 'Clerk', 2500, 0, 10);
INSERT INTO EMP VALUES (103, 'Karen Page', 'Manager', 4500, 0, 30);
INSERT INTO EMP VALUES (102, 'Foggy Nelson', 'Salesperson', 3000, 500, 20);
INSERT INTO EMP VALUES (104, 'Elektra Natchios', 'Salesperson', 2700, 400, 20);
INSERT INTO EMP VALUES (105, 'Wilson Fisk', 'Clerk', 2200, 0, 10);
SELECT EMPNO,ENAME FROM EMP WHERE DEPTNO=10;
SELECT ENAME FROM EMP WHERE SALARY>2000;
SELECT ENAME,JOB_NAME FROM EMP WHERE JOB_NAME IN('Salesperson','Clerk');
SELECT * FROM EMP;  
UPDATE EMP SET COMMISSION=NULL WHERE COMMISSION=0;
SELECT ENAME FROM EMP WHERE SALARY>=2000 AND SALARY<=3000;
SELECT EMPNO,ENAME FROM EMP WHERE DEPTNO IN (10,20,30);
SELECT EMPNO,ENAME FROM EMP WHERE COMMISSION IS NULL;
SELECT * FROM EMP ORDER BY DEPTNO ASC,SALARY DESC;
SELECT ENAME FROM EMP WHERE LOWER(ENAME) LIKE '%a%a%';
SELECT MAX(SALARY),MIN(SALARY),AVG(SALARY) FROM EMP WHERE DEPTNO=10;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=20;
SELECT SUM(SALARY) FROM EMP WHERE JOB_NAME='Clerk';
SELECT SYSDATE FROM DUAL;
SELECT (12*12)/13 FROM DUAL;