SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MONTH') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY,DD-MONTH-YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH:MM:SS AM') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'FRIDAY') FROM DUAL;
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE+3,'DAY') FROM DUAL;
CREATE TABLE NEW_EMPS(
    EMP_NO INT,
    NAMES VARCHAR2(20),
    DOJ DATE
);
INSERT INTO NEW_EMPS VALUES(101, 'JOHN CENA', TO_DATE('12-12-2002', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(102, 'ROMAN REIGNS', TO_DATE('12-11-2012', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(103, 'AJ STYLES', TO_DATE('31-01-2016', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(104, 'RANDY ORTON', TO_DATE('25-04-2002', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(105, 'CM PUNK', TO_DATE('24-07-2006', 'DD-MM-YYYY'));
SELECT DOJ FROM NEW_EMPS;
INSERT INTO NEW_EMPS VALUES(106, 'SETH ROLLINS', TO_DATE('15-07-2013', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(107, 'DEAN AMBROSE', TO_DATE('22-07-2013', 'DD-MM-YYYY'));
SELECT NAMES FROM NEW_EMPS WHERE TO_CHAR(DOJ,'DY')='MON';
INSERT INTO NEW_EMPS VALUES(108, 'CODY RHODES', TO_DATE('07-04-2025', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(109, 'THE ROCK', TO_DATE('12-04-2025', 'DD-MM-YYYY'));
INSERT INTO NEW_EMPS VALUES(110, 'SHAWN MICHEALS', TO_DATE('21-03-2025', 'DD-MM-YYYY'));
SELECT NAMES FROM NEW_EMPS WHERE TO_CHAR(DOJ,'MM-YY')=TO_CHAR(SYSDATE,'MM-YY');
SELECT NAMES FROM NEW_EMPS WHERE DOJ>=SYSDATE-30;

CREATE TABLE TRAIN (
    TRAINNO NUMBER(6) PRIMARY KEY,
    DATE_OF_DEPARTURE DATE,
    TIME_OF_DEPARTURE TIMESTAMP,
    TIME_OF_ARRIVAL TIMESTAMP
);
INSERT INTO TRAIN VALUES (101101, SYSDATE, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '2' HOUR);
INSERT INTO TRAIN VALUES (101102, SYSDATE + 1, SYSTIMESTAMP + INTERVAL '1' DAY, SYSTIMESTAMP + INTERVAL '3' DAY);
INSERT INTO TRAIN VALUES (101103, SYSDATE - 1, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '20' HOUR);
INSERT INTO TRAIN VALUES (101104, SYSDATE + 2, SYSTIMESTAMP + INTERVAL '2' DAY, SYSTIMESTAMP + INTERVAL '5' DAY);
INSERT INTO TRAIN VALUES (101105, SYSDATE, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' HOUR);
SELECT * FROM TRAIN;
SELECT TRAINNO, TIME_OF_DEPARTURE, TIME_OF_ARRIVAL FROM TRAIN;
SELECT * FROM TRAIN WHERE TO_CHAR(TIME_OF_ARRIVAL, 'AM') = 'PM';
SELECT TRAINNO FROM TRAIN WHERE TIME_OF_DEPARTURE BETWEEN SYSTIMESTAMP AND SYSTIMESTAMP + INTERVAL '1' HOUR;