--TABLE DEPT (DEPTNO, DEPTNAME)
--TABLE EMP (EMPNO, EMPNAME, DEPTNO, JOB, SALARY): DEPTNO is a foreign
--key w.r.t to DEPT Table.
CREATE TABLE DEPT(
    DEPTNO INT PRIMARY KEY,
    DEPTNAME VARCHAR2(25)
); 
CREATE TABLE EMPL(
    EMPNO INT PRIMARY KEY,
    EMPNAME VARCHAR(30),
    DEPTNO INT,
    EJOB VARCHAR(20),
    SALARY FLOAT
);
INSERT INTO DEPT VALUES (10, 'ACCOUNTING');
INSERT INTO DEPT VALUES (20, 'RESEARCH');
INSERT INTO DEPT VALUES (30, 'SALES');
INSERT INTO DEPT VALUES (40, 'OPERATIONS');

INSERT INTO EMPL VALUES (101, 'Alice', 10, 'Manager', 5000);
INSERT INTO EMPL VALUES (102, 'Bob', 20, 'Analyst', 3000);
INSERT INTO EMPL VALUES (103, 'Charlie', 20, 'Clerk', 1500);
INSERT INTO EMPL VALUES (104, 'David', 30, 'Salesman', 2500);
INSERT INTO EMPL VALUES (105, 'Eve', 30, 'Salesman', 2800);
INSERT INTO EMPL VALUES (106, 'Frank', 30, 'Manager', 4000);
INSERT INTO EMPL VALUES (107, 'Grace', 40, 'Clerk', 1300);
INSERT INTO EMPL VALUES (108, 'Heidi', 10, 'Clerk', 1600);
INSERT INTO EMPL VALUES (109, 'Ivan', 20, 'Manager', 4500);
INSERT INTO EMPL VALUES (110, 'Judy', 20, 'Analyst', 3200);
SELECT * FROM EMPL;
SELECT COUNT(*) FROM EMPL;
SELECT COUNT(DISTINCT DEPTNO) FROM EMPL;
SELECT D.DEPTNAME,E.EMPNAME FROM DEPT D JOIN EMPL E ON D.DEPTNO=E.DEPTNO;
SELECT SUM(SALARY),MAX(SALARY),MIN(SALARY) FROM EMPL WHERE DEPTNO=30;
SELECT EMPNAME FROM EMPL WHERE SALARY=(SELECT MAX(SALARY) FROM EMPL);
SELECT D.DEPTNAME,SUM(E.SALARY) AS TOTAL_SALARY FROM EMPL E JOIN DEPT D ON E.DEPTNO = D.DEPTNO GROUP BY D.DEPTNAME;
SELECT SUM(SALARY),EJOB FROM EMPL GROUP BY EJOB;
SELECT D.DEPTNAME,E.EJOB,SUM(E.SALARY) AS TOTAL_SALARY FROM EMPL E JOIN DEPT D ON E.DEPTNO = D.DEPTNO GROUP BY D.DEPTNAME,E.EJOB;
SELECT AVG(SALARY),EJOB FROM EMPL WHERE DEPTNO=20 GROUP BY EJOB;
SELECT SUM(SALARY),EJOB FROM EMPL WHERE EJOB NOT IN('Manager','Salesman') GROUP BY EJOB;
SELECT AVG(SALARY),EJOB FROM EMPL WHERE DEPTNO=20 GROUP BY EJOB HAVING AVG(SALARY)>2000 ORDER BY AVG(SALARY) DESC;
SELECT COUNT(*),DEPTNO FROM EMPL WHERE DEPTNO NOT IN(10) GROUP BY DEPTNO HAVING COUNT(*)>1 ORDER BY COUNT(*) DESC;
SELECT COUNT(*),E.DEPTNO,D.DEPTNAME FROM EMPL E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE D.DEPTNAME!='OPERATIONS' GROUP BY E.DEPTNO,D.DEPTNAME HAVING COUNT(*)>1 ORDER BY COUNT(*) DESC;
SELECT COUNT(*),DEPTNO,EJOB FROM EMPL GROUP BY DEPTNO,EJOB ORDER BY DEPTNO;
SELECT D.DEPTNAME,E.EMPNAME FROM EMPL E RIGHT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
SELECT D.DEPTNAME,E.EMPNAME FROM EMPL E LEFT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
SELECT D.DEPTNAME,E.EMPNAME FROM EMPL E FULL OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
