--Create table Student (Rno, Name, DOB, Gender, Class, College,City, Marks) 
CREATE TABLE STUDENTS(
RNO INT,
NAMES VARCHAR(20),
DOB DATE,
GENDER VARCHAR(6),
CLASS INT,
COLLEGE VARCHAR(50),
CITY VARCHAR(10),
MARKS FLOAT
);
INSERT INTO STUDENTS VALUES(102,'ESHAAN SINGLA',TO_DATE('28-07-2005','DD-MM-YYYY'),'MALE',2,'TIET','PATIALA',99.1);
INSERT INTO STUDENTS VALUES(103,'DINAH MADANI',TO_DATE('08-10-2004','DD-MM-YYYY'),'FEMALE',1,'TIET','CHANDIGARH',94.1);
INSERT INTO STUDENTS VALUES(104,'FRANK CASTLE',TO_DATE('02-07-2006','DD-MM-YYYY'),'MALE',3,'TIET','KARNAL',98.15);
INSERT INTO STUDENTS VALUES(105,'KAREN PAGE',TO_DATE('28-09-2005','DD-MM-YYYY'),'FEMALE',2,'TIET','BATHINDA',90.1);
INSERT INTO STUDENTS VALUES(106,'MARSHALL MATHERS',TO_DATE('15-08-2005','DD-MM-YYYY'),'MALE',4,'TIET','PATIALA',33.1);

SELECT * FROM STUDENTS ORDER BY MARKS DESC;
DESCRIBE STUDENTS;
SELECT * FROM STUDENTS WHERE CITY='PATIALA';
UPDATE STUDENTS SET MARKS=95 WHERE RNO=106;
UPDATE STUDENTS SET CITY='NEW YORK' WHERE RNO=106;
UPDATE STUDENTS SET NAMES='WALTER WHITE' WHERE RNO=106;
DELETE FROM STUDENTS WHERE CITY='NEW YORK';
DELETE FROM STUDENTS WHERE MARKS<95;

